openapi: 3.0.1
info:
  title: monster-beholder-zombie
  x-cortex-tag: monster-beholder-zombie
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: undead
    challenge_rating: 5
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-beholder-zombie
      alias: github-token-test
